language: generic 
services:
  - docker

before_install:
  - docker build -t subhash06582/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true subhash06582/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-131959706776"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
